### PR TITLE
Feature: publications

### PR DESCRIPTION
**Pull request by ajliu**

### CODE REVIEW

**Comment by ajliu** [comment]
woops I accidentally committed your branch into mine

**Comment by ajliu** [comment]
oh well idk how to fix it

**Comment by chsahit** [comment]
This is really pretty, the only thing I'd say is that the 2017 papers should appear before the 2016 ones (reverse chronological).

**Comment by ajliu** [comment]
@chsahit wait isn't that the case? Where is it not like that??

**Pull request merged**
